version: "3"

services:
  telegraf:
    image: telegraf:1.5.2
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: telegraf
    networks:
      - monitoring-tier
    deploy:
      mode: global
  
  influxdb:
    image: influxdb:1.4.3-alpine
    restart: always
    volumes:
      - "influxdb-data:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=telegraf
    hostname: influxdb
    networks:
      - monitoring-tier
    deploy:
      placement:
        constraints:
          - node.role==manager

  grafana:
    image: grafana/grafana:5.0.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://grafana.example.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=alert@gmail.com
      - GF_SMTP_PASSWORD=password
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=alert@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
    hostname: grafana
    networks:
      - monitoring-tier
    deploy:
      placement:
        constraints:
          - node.role==manager

volumes:
  influxdb-data:
  grafana-data:
networks:
  monitoring-tier: